# BBC FY22 Q4

In [1]:
bbc1=r'/kaggle/input/bbc-q4/BBCFY21Q4.csv'
bbc2=r'/kaggle/input/bbc-q4/BBCFY22Q4.csv'

In [2]:
import pandas as pd

bbc1=pd.read_csv(bbc1)
bbc1.head()

,GL Account,GL Description,Allocated Budget,Actual,% Used,Available,Budget Officer
0,10602-08-278910000-503001,Sales Food - Pastries : BBC,-1468.0,0.00,0.00,-1468.00,303100
1,10602-08-278910000-503002,Sales Drink - Alternative : BBC,-3923.0,-1348.43,34.37,-2574.57,303100
2,10602-08-278910000-503004,Sales Drink - Soda : BBC,-1239.0,-420.12,33.91,-818.88,303100
3,10602-08-278910000-503005,Sales Food - Candy/Gum : BBC,-826.0,-365.22,44.22,-460.78,303100
4,10602-08-278910000-503006,Sales Food - Snacks/Treats : BBC,-1130.0,0.00,0.00,-1130.00,303100

In [3]:
from babel.numbers import format_currency

bbc1=bbc1[['GL Account', 'GL Description', 'Allocated Budget', 'Actual', '% Used']]
bbc1.rename(columns={'Allocated Budget': 'Budget', 'GL Description': 'Revenue'}, inplace=True)
bbc1.insert(5, " ", " ") 
bbc1.head()

,GL Account,Revenue,Budget,Actual,% Used,
0,10602-08-278910000-503001,Sales Food - Pastries : BBC,-1468.0,0.00,0.00,
1,10602-08-278910000-503002,Sales Drink - Alternative : BBC,-3923.0,-1348.43,34.37,
2,10602-08-278910000-503004,Sales Drink - Soda : BBC,-1239.0,-420.12,33.91,
3,10602-08-278910000-503005,Sales Food - Candy/Gum : BBC,-826.0,-365.22,44.22,
4,10602-08-278910000-503006,Sales Food - Snacks/Treats : BBC,-1130.0,0.00,0.00,

# BBC FY21 Q4

In [4]:
#READ PREVIOUS QRT DATA:
bbc2=pd.read_csv(bbc2)
bbc2=bbc2[['GL Account', 'Allocated Budget', 'Actual', '% Used']]
bbc2.head()

                  GL Account  Allocated Budget   Actual  % Used
0  10602-08-278910000-420100               0.0     0.00    0.00
1  10602-08-278910000-503002          -14295.0 -2518.70   17.62
2  10602-08-278910000-507000            -500.0  -132.28   26.46
3  10602-08-278910000-515002           -2125.0  -937.55   44.12
4  10602-08-278910000-540050          -20075.0 -5219.22   26.00

In [5]:
bbc2.rename(columns={'Allocated Budget': ' Budget', 'Actual': ' Actual','% Used': ' % Used'}, inplace=True)
bbc2.insert(4, " . ", " ") 
bbc2.head()

                  GL Account   Budget   Actual   % Used  .
0  10602-08-278910000-420100      0.0     0.00     0.00
1  10602-08-278910000-503002 -14295.0 -2518.70    17.62
2  10602-08-278910000-507000   -500.0  -132.28    26.46
3  10602-08-278910000-515002  -2125.0  -937.55    44.12
4  10602-08-278910000-540050 -20075.0 -5219.22    26.00

# Join Data with Previous Year Data

In [6]:
bbc=bbc1.merge(bbc2, on='GL Account')
bbc.head()

,GL Account,Revenue,Budget,Actual,% Used,,Budget,Actual,% Used,.
0,10602-08-278910000-503002,Sales Drink - Alternative : BBC,-3923.0,-1348.43,34.37,,-14295.0,-2518.70,17.62,
1,10602-08-278910000-507000,Sales Merchandise : BBC,-2079.0,-92.14,4.43,,-500.0,-132.28,26.46,
2,10602-08-278910000-515002,Table Games : BBC,-1096.0,-323.50,29.52,,-2125.0,-937.55,44.12,
3,10602-08-278910000-540050,Billiards : BBC,-11180.0,-2970.82,26.57,,-20075.0,-5219.22,26.00,
4,10602-08-278910000-540055,Bowling : BBC,-46661.0,-23186.25,49.69,,-184295.0,-39398.74,21.38,

In [7]:
bbc=bbc.rename(columns={'GL Account':'Object Code'})
bbc.head()

,Object Code,Revenue,Budget,Actual,% Used,,Budget,Actual,% Used,.
0,10602-08-278910000-503002,Sales Drink - Alternative : BBC,-3923.0,-1348.43,34.37,,-14295.0,-2518.70,17.62,
1,10602-08-278910000-507000,Sales Merchandise : BBC,-2079.0,-92.14,4.43,,-500.0,-132.28,26.46,
2,10602-08-278910000-515002,Table Games : BBC,-1096.0,-323.50,29.52,,-2125.0,-937.55,44.12,
3,10602-08-278910000-540050,Billiards : BBC,-11180.0,-2970.82,26.57,,-20075.0,-5219.22,26.00,
4,10602-08-278910000-540055,Bowling : BBC,-46661.0,-23186.25,49.69,,-184295.0,-39398.74,21.38,

# Split Revenue and Expense

In [8]:
#bbc['dept']  =   bbc['Object Code'].astype(str).str[9:14]
bbc['Object Code']  = bbc['Object Code'].astype(str).str[-6:].astype(int)
bbc.head(7)

,Object Code,Revenue,Budget,Actual,% Used,,Budget,Actual,% Used,.
0,503002,Sales Drink - Alternative : BBC,-3923.0,-1348.43,34.37,,-14295.0,-2518.70,17.62,
1,507000,Sales Merchandise : BBC,-2079.0,-92.14,4.43,,-500.0,-132.28,26.46,
2,515002,Table Games : BBC,-1096.0,-323.50,29.52,,-2125.0,-937.55,44.12,
3,540050,Billiards : BBC,-11180.0,-2970.82,26.57,,-20075.0,-5219.22,26.00,
4,540055,Bowling : BBC,-46661.0,-23186.25,49.69,,-184295.0,-39398.74,21.38,
5,540057,Bowling - Leagues : BBC,-7065.0,-2124.00,30.06,,0.0,-2700.00,0.00,
6,540058,Bowling - P.E. : BBC,-20792.0,-4793.75,23.06,,-27500.0,-9561.00,34.77,

#### Revenue

In [9]:
import warnings
warnings.filterwarnings("ignore")

intCols=['Budget','Actual', ' Budget', ' Actual']

In [10]:
revDF=bbc[bbc['Object Code'] < 600_000].sort_values(by='Object Code')
revDF.loc['Total']= revDF[intCols].sum()

revDF["Budget"] =  revDF["Budget"]*-1
revDF[" Budget"] =  revDF[" Budget"]*-1
revDF["Actual"] = revDF["Actual"]*-1
revDF[" Actual"] = revDF[" Actual"]*-1

revDF["Budget"] =  revDF["Budget"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
revDF[" Budget"] = revDF[" Budget"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
revDF["Actual"] = revDF["Actual"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
revDF[" Actual"] = revDF[" Actual"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
revDF.head()

,Object Code,Revenue,Budget,Actual,% Used,,Budget,Actual,% Used,.
0,503002.0,Sales Drink - Alternative : BBC,"$3,923.00","$1,348.43",34.37,,"$14,295.00","$2,518.70",17.62,
1,507000.0,Sales Merchandise : BBC,"$2,079.00",$92.14,4.43,,$500.00,$132.28,26.46,
2,515002.0,Table Games : BBC,"$1,096.00",$323.50,29.52,,"$2,125.00",$937.55,44.12,
3,540050.0,Billiards : BBC,"$11,180.00","$2,970.82",26.57,,"$20,075.00","$5,219.22",26.00,
4,540055.0,Bowling : BBC,"$46,661.00","$23,186.25",49.69,,"$184,295.00","$39,398.74",21.38,

#### Expenses

In [11]:
expDF=bbc[bbc['Object Code']>600_000].sort_values(by='Object Code')
expDF = expDF.rename(columns={'Revenue': 'Expenses'})
expDF.loc['Total']= expDF[intCols].sum()

expDF["Budget"] = expDF["Budget"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
expDF[" Budget"] = expDF[" Budget"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
expDF["Actual"] = expDF["Actual"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
expDF[" Actual"] = expDF[" Actual"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
expDF.head()

,Object Code,Expenses,Budget,Actual,% Used,,Budget,Actual,% Used,.
12,615100.0,Civil Service- Exempt : BBC,"$60,000.00","$52,872.00",88.12,,"$53,401.00","$55,763.64",104.42,
13,615200.0,CS Non-Exempt : BBC,"$49,000.00","$48,295.62",98.56,,"$48,296.00","$49,367.48",102.22,
14,625000.0,Student Wages : BBC,"$64,300.00","$47,967.73",74.60,,"$30,711.00","$22,336.00",72.73,
15,625200.0,Student Wages - FWS : BBC,$0.00,"$2,459.67",0.00,,$0.00,"$1,250.00",0.00,
16,641000.0,Medicare/FICA : BBC,"$2,965.00","$1,570.29",52.96,,"$2,034.00","$1,552.42",76.32,

# Create Final Report

In [12]:
'''
#!pip install xlsxwriter
import xlsxwriter

fileName='Campus.xlsx'
year='FY22'
pYear='FY21'
header=year+' - Q3 Financials as of 5/11/22'
ag='Agency SFC'
bbc='Bond BBC'
sfcBond='BOND SFC'
startrow=4
startcol=1

#CHANGE NOTHING BELOW:
writer = pd.ExcelWriter(fileName, engine='xlsxwriter')
workbook  = writer.book

header_format = workbook.add_format( 
    {
        'bold': True,
        'text_wrap': False,
        'valign': 'left',
        #'border': 'blue',
        # 'fg_color': '#D7E4BC',
        #'bg_color': '#edbd93',
        #'border': 1
    }
)

bold = workbook.add_format( 
    {
        'bold': True,
        'text_wrap': False,
        'valign': 'center',
    }
)

boldBorderUnder = workbook.add_format( 
    {
        'bold': True,
        'text_wrap': False,
        'valign': 'right',
        'border': 1,
        'bg_color': '#e6ffff',
        #'border':'1px solid', 
    }
)

def highlight_everyother(s):
    return ['background-color: lightblue' if x%2==1 else ''
              for x in range(len(s))]

def bold_last(x):
    return ['font-weight: bold' if v == x.iloc[-1] else '' 
            for v in x]

def highlight_last(x):
    return ['background-color: yellow' if v == x.iloc[-1] else '' 
            for v in x]

revDFs=revDF.style.set_properties(**{'border': '1px blue solid !important',  'text-align': 'center', 'valign': 'center','valign': 'center', 'color':'black', 'border-width':'1px'}).apply(highlight_everyother).apply(bold_last)
expDFs=expDF.style.set_properties(**{'border': '1px blue solid !important',  'text-align': 'center', 'valign': 'center','valign': 'center', 'color':'black', 'border-width':'1px'}).apply(highlight_everyother).apply(bold_last)
'''

"\n#!pip install xlsxwriter\nimport xlsxwriter\n\nfileName='Campus.xlsx'\nyear='FY22'\npYear='FY21'\nheader=year+' - Q3 Financials as of 5/11/22'\nag='Agency SFC'\nbbc='Bond BBC'\nsfcBond='BOND SFC'\nstartrow=4\nstartcol=1\n\n#CHANGE NOTHING BELOW:\nwriter = pd.ExcelWriter(fileName, engine='xlsxwriter')\nworkbook  = writer.book\n\nheader_format = workbook.add_format( \n    {\n        'bold': True,\n        'text_wrap': False,\n        'valign': 'left',\n        #'border': 'blue',\n        # 'fg_color': '#D7E4BC',\n        #'bg_color': '#edbd93',\n        #'border': 1\n    }\n)\n\nbold = workbook.add_format( \n    {\n        'bold': True,\n        'text_wrap': False,\n        'valign': 'center',\n    }\n)\n\nboldBorderUnder = workbook.add_format( \n    {\n        'bold': True,\n        'text_wrap': False,\n        'valign': 'right',\n        'border': 1,\n        'bg_color': '#e6ffff',\n        #'border':'1px solid', \n    }\n)\n\ndef highlight_everyother(s):\n    return ['background-color: lightblue' if x%2==1 else ''\n              for x in range(len(s))]\n\ndef bold_last(x):\n    return ['font-weight: bold' if v == x.iloc[-1] else '' \n            for v in x]\n\ndef highlight_last(x):\n    return ['background-color: yellow' if v == x.iloc[-1] else '' \n            for v in x]\n\nrevDFs=revDF.style.set_properties(**{'border': '1px blue solid !important',  'text-align': 'center', 'valign': 'center','valign': 'center', 'color':'black', 'border-width':'1px'}).apply(highlight_everyother).apply(bold_last)\nexpDFs=expDF.style.set_properties(**{'border': '1px blue solid !important',  'text-align': 'center', 'valign': 'center','valign': 'center', 'color':'black', 'border-width':'1px'}).apply(highlight_everyother).apply(bold_last)\n"

# Generator Report

In [13]:
'''
#AGENCY:
revDFs.to_excel(writer, sheet_name=bbc, startrow=startrow, startcol=startcol, index=False)
expDFs.to_excel(writer, sheet_name=bbc, startrow=startrow+len(revDF)+2, startcol=startcol, index=False)

worksheet1 = writer.sheets[bbc]
worksheet1.write(1, 0, 'Campus '+ bbc, header_format)
worksheet1.write(2, 0, header, header_format)
worksheet1.write(3, 4, year, bold)
worksheet1.write(3, 8, pYear, bold)
worksheet1.write(3, 10, pYear, bold)
worksheet1.write(startrow+len(revDF), 2, 'Total Income', boldBorderUnder)
worksheet1.write(startrow+len(revDF)+len(expDF)+2, 2, 'Total Expenses', boldBorderUnder)

#SAVE SHEET:
writer.save()
print("New Excel Report File created: ", fileName)
'''

'\n#AGENCY:\nrevDFs.to_excel(writer, sheet_name=bbc, startrow=startrow, startcol=startcol, index=False)\nexpDFs.to_excel(writer, sheet_name=bbc, startrow=startrow+len(revDF)+2, startcol=startcol, index=False)\n\nworksheet1 = writer.sheets[bbc]\nworksheet1.write(1, 0, \'Campus \'+ bbc, header_format)\nworksheet1.write(2, 0, header, header_format)\nworksheet1.write(3, 4, year, bold)\nworksheet1.write(3, 8, pYear, bold)\nworksheet1.write(3, 10, pYear, bold)\nworksheet1.write(startrow+len(revDF), 2, \'Total Income\', boldBorderUnder)\nworksheet1.write(startrow+len(revDF)+len(expDF)+2, 2, \'Total Expenses\', boldBorderUnder)\n\n#SAVE SHEET:\nwriter.save()\nprint("New Excel Report File created: ", fileName)\n'