# Qrt Report on one Tab

In [1]:
import pandas as pd
admin1=r'/kaggle/input/finalqrt/GLBA.csv'
admin1=pd.read_csv(admin1)
admin1.head()

,GL Account,GL Description,Allocated Budget,Actual,% Used,Available,Budget Officer
0,10904-05-298000000-106500,A/R Agency : Campus Rec Administrative,0,100.00,0.0,-823.00,1234567
1,10904-05-298000000-240000,Deferred Revenues : Campus Rec Administrative,0,39.00,0.0,-35.00,1234567
2,10904-05-298000000-429999,Fund Balance - Cur Unrest : Campus Rec Adminis...,0,-438252.78,0.0,438252.78,1234567
3,10904-05-298000000-595000,Misc Revenue : Campus Rec Administrative,0,0.00,0.0,0.00,1234567
4,10904-05-298000000-595100,Investment Revenue : Campus Rec Administrative,0,-185.10,0.0,185.10,1234567

In [2]:
from babel.numbers import format_currency

admin1=admin1[['GL Account', 'GL Description', 'Allocated Budget', 'Actual', '% Used']]
admin1.rename(columns={'Allocated Budget': 'Budget', 'GL Description': 'Revenue'}, inplace=True)
admin1.insert(5, " ", " ") 
admin1.head()

,GL Account,Revenue,Budget,Actual,% Used,
0,10904-05-298000000-106500,A/R Agency : Campus Rec Administrative,0,100.00,0.0,
1,10904-05-298000000-240000,Deferred Revenues : Campus Rec Administrative,0,39.00,0.0,
2,10904-05-298000000-429999,Fund Balance - Cur Unrest : Campus Rec Adminis...,0,-438252.78,0.0,
3,10904-05-298000000-595000,Misc Revenue : Campus Rec Administrative,0,0.00,0.0,
4,10904-05-298000000-595100,Investment Revenue : Campus Rec Administrative,0,-185.10,0.0,

# Previous Year Data

In [3]:
#READ PREVIOUS QRT DATA:
admin2=r'/kaggle/input/finalqrt/GLBA1.csv'
admin2=pd.read_csv(admin2)
admin2=admin2[['GL Account', 'Allocated Budget', 'Actual', '% Used']]
admin2.head()

                  GL Account  Allocated Budget     Actual  % Used
0  10904-05-298000000-106500                 0     645.00     0.0
1  10904-05-298000000-240000                 0       0.00     0.0
2  10904-05-298000000-429999                 0 -438252.78     0.0
3  10904-05-298000000-595000                 0       0.00     0.0
4  10904-05-298000000-595100                 0       0.00     0.0

In [4]:
admin2.rename(columns={'Allocated Budget': 'Budget1', 'Actual': 'Actual1','% Used': '% Used1'}, inplace=True)
admin2.head()

                  GL Account  Budget1    Actual1  % Used1
0  10904-05-298000000-106500        0     645.00      0.0
1  10904-05-298000000-240000        0       0.00      0.0
2  10904-05-298000000-429999        0 -438252.78      0.0
3  10904-05-298000000-595000        0       0.00      0.0
4  10904-05-298000000-595100        0       0.00      0.0

# Join Data with Previous Year Data

In [5]:
data=admin1.merge(admin2, on='GL Account')
data.head()

,GL Account,Revenue,Budget,Actual,% Used,,Budget1,Actual1,% Used1
0,10904-05-298000000-106500,A/R Agency : Campus Rec Administrative,0,100.00,0.0,,0,645.00,0.0
1,10904-05-298000000-240000,Deferred Revenues : Campus Rec Administrative,0,39.00,0.0,,0,0.00,0.0
2,10904-05-298000000-429999,Fund Balance - Cur Unrest : Campus Rec Adminis...,0,-438252.78,0.0,,0,-438252.78,0.0
3,10904-05-298000000-595000,Misc Revenue : Campus Rec Administrative,0,0.00,0.0,,0,0.00,0.0
4,10904-05-298000000-595100,Investment Revenue : Campus Rec Administrative,0,-185.10,0.0,,0,0.00,0.0

In [6]:
data=data.rename(columns={'GL Account':'Object Code'})
data.head()

,Object Code,Revenue,Budget,Actual,% Used,,Budget1,Actual1,% Used1
0,10904-05-298000000-106500,A/R Agency : Campus Rec Administrative,0,100.00,0.0,,0,645.00,0.0
1,10904-05-298000000-240000,Deferred Revenues : Campus Rec Administrative,0,39.00,0.0,,0,0.00,0.0
2,10904-05-298000000-429999,Fund Balance - Cur Unrest : Campus Rec Adminis...,0,-438252.78,0.0,,0,-438252.78,0.0
3,10904-05-298000000-595000,Misc Revenue : Campus Rec Administrative,0,0.00,0.0,,0,0.00,0.0
4,10904-05-298000000-595100,Investment Revenue : Campus Rec Administrative,0,-185.10,0.0,,0,0.00,0.0

# Split Revenue and Expense

In [7]:
data['dept']  =   data['Object Code'].astype(str).str[9:14]
data['Object Code']  = data['Object Code'].astype(str).str[-6:].astype(int)
data

,Object Code,Revenue,Budget,Actual,% Used,,Budget1,Actual1,% Used1,dept
0,106500,A/R Agency : Campus Rec Administrative,0,100.00,0.00,,0,645.00,0.0,29800
1,240000,Deferred Revenues : Campus Rec Administrative,0,39.00,0.00,,0,0.00,0.0,29800
2,429999,Fund Balance - Cur Unrest : Campus Rec Adminis...,0,-438252.78,0.00,,0,-438252.78,0.0,29800
3,595000,Misc Revenue : Campus Rec Administrative,0,0.00,0.00,,0,0.00,0.0,29800
4,595100,Investment Revenue : Campus Rec Administrative,0,-185.10,0.00,,0,0.00,0.0,29800
...,...,...,...,...,...,...,...,...,...,...
64,991210,UMB - Personal Services : Intramurals,0,0.00,0.00,,0,0.00,0.0,29890
65,540004,Service Rev - Student : Special Events,8300,0.00,0.00,,0,0.00,0.0,29880
66,551400,Fees - Damage Reimburse : Special Events,8022,405.48,5.05,,0,0.00,0.0,29880
67,991000,UMBRELLA BUDGET : Special Events,8000,1766.14,22.08,,8300,0.00,0.0,29880
68,991210,UMB - Personal Services : Special Events,0,0.00,0.00,,8022,39.90,0.5,29880

#### Revenue

In [8]:
import warnings
warnings.filterwarnings("ignore")

intCols=['Budget','Actual', '% Used', 'Budget1', 'Actual1', '% Used1']

In [9]:
revDF=data[data['Object Code'] < 600_000].sort_values(by='Object Code')
revDF.loc['Total']= revDF[intCols].sum()

revDF["Budget"] =  revDF["Budget"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
revDF["Budget1"] = revDF["Budget1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
revDF["Actual"] = revDF["Actual"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
revDF["Actual1"] = revDF["Actual1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
revDF.head()

,Object Code,Revenue,Budget,Actual,% Used,,Budget1,Actual1,% Used1,dept
0,106500.0,A/R Agency : Campus Rec Administrative,$0.00,$100.00,0.0,,$0.00,$645.00,0.0,29800
46,106500.0,A/R Agency : Outdoor Center,$0.00,-$49.00,0.0,,$0.00,$0.00,0.0,29840
1,240000.0,Deferred Revenues : Campus Rec Administrative,$0.00,$39.00,0.0,,$0.00,$0.00,0.0,29800
2,429999.0,Fund Balance - Cur Unrest : Campus Rec Adminis...,$0.00,"-$438,252.78",0.0,,$0.00,"-$438,252.78",0.0,29800
31,429999.0,Fund Balance - Cur Unrest : Sports Club Poolin...,"$121,020.00",$0.00,0.0,,$0.00,"-$199,766.41",0.0,29840

#### Expenses

In [10]:
expDF=data[data['Object Code']>600_000].sort_values(by='Object Code')
expDF = expDF.rename(columns={'Revenue': 'Expenses'})
expDF.loc['Total']= expDF[intCols].sum()

#expDF["Budget"] = expDF1["Budget"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#expDF["Budget1"] = expDF["Budget1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#expDF["Actual"] = expDF["Actual"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#expDF["Actual1"] = expDF["Actual1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
expDF.head()

,Object Code,Expenses,Budget,Actual,% Used,,Budget1,Actual1,% Used1,dept
5,902000.0,Non-Mandatory TRF's : Campus Rec Administrative,0.0,-626490.00,0.0,,0.0,-626490.00,0.00,29800
62,991000.0,UMBRELLA BUDGET : Intramurals,0.0,-200.00,0.0,,8000.0,1766.14,22.08,29890
61,991000.0,UMBRELLA BUDGET : Intramurals,0.0,-200.00,0.0,,5920.0,10.94,0.18,29890
57,991000.0,UMBRELLA BUDGET : Competitive Sports,0.0,-6275.00,0.0,,4840.0,489.68,10.12,29860
55,991000.0,UMBRELLA BUDGET : Trips & Travel,4840.0,880.87,18.2,,0.0,0.00,0.00,29850

# Creating Final Report

In [11]:
'''
#!pip install xlsxwriter
import xlsxwriter

fileName='Campus.xlsx'
year='FY22'
pYear='FY21'
header=year+' - Q3 Financials as of 5/11/22'
ag='Agency SFC'
bbc='Bond BBC'
sfcBond='BOND SFC'
startrow=4
startcol=1

#CHANGE NOTHING BELOW:
writer = pd.ExcelWriter(fileName, engine='xlsxwriter')
workbook  = writer.book

header_format = workbook.add_format( 
    {
        'bold': True,
        'text_wrap': False,
        'valign': 'left',
        # 'fg_color': '#D7E4BC',
        #'bg_color': '#edbd93',
        #'border': 1
    }
)

bold = workbook.add_format( 
    {
        'bold': True,
        'text_wrap': False,
        'valign': 'center',
    }
)

boldBorderUnder = workbook.add_format( 
    {
        'bold': True,
        'text_wrap': True,
        'valign': 'center',
        'border': 1,
        'bg_color': 'yellow',
    }
)

def highlight_everyother(s):
    return ['background-color: lightblue' if x%2==1 else ''
              for x in range(len(s))]

def bold_last(x):
    return ['font-weight: bold' if v == x.iloc[-1] else '' 
            for v in x]

def highlight_last(x):
    return ['background-color: yellow' if v == x.iloc[-1] else '' 
            for v in x]

revDFs=revDF.style.set_properties(**{'border': '1px blue solid !important','color':'black', 'border-width':'1px'}).apply(highlight_everyother).apply(bold_last)
expDFs=expDF.style.set_properties(**{'border': '1px blue solid !important','color':'black', 'border-width':'1px'}).apply(highlight_everyother).apply(bold_last)
'''

"\n#!pip install xlsxwriter\nimport xlsxwriter\n\nfileName='Campus.xlsx'\nyear='FY22'\npYear='FY21'\nheader=year+' - Q3 Financials as of 5/11/22'\nag='Agency SFC'\nbbc='Bond BBC'\nsfcBond='BOND SFC'\nstartrow=4\nstartcol=1\n\n#CHANGE NOTHING BELOW:\nwriter = pd.ExcelWriter(fileName, engine='xlsxwriter')\nworkbook  = writer.book\n\nheader_format = workbook.add_format( \n    {\n        'bold': True,\n        'text_wrap': False,\n        'valign': 'left',\n        # 'fg_color': '#D7E4BC',\n        #'bg_color': '#edbd93',\n        #'border': 1\n    }\n)\n\nbold = workbook.add_format( \n    {\n        'bold': True,\n        'text_wrap': False,\n        'valign': 'center',\n    }\n)\n\nboldBorderUnder = workbook.add_format( \n    {\n        'bold': True,\n        'text_wrap': True,\n        'valign': 'center',\n        'border': 1,\n        'bg_color': 'yellow',\n    }\n)\n\ndef highlight_everyother(s):\n    return ['background-color: lightblue' if x%2==1 else ''\n              for x in range(len(s))]\n\ndef bold_last(x):\n    return ['font-weight: bold' if v == x.iloc[-1] else '' \n            for v in x]\n\ndef highlight_last(x):\n    return ['background-color: yellow' if v == x.iloc[-1] else '' \n            for v in x]\n\nrevDFs=revDF.style.set_properties(**{'border': '1px blue solid !important','color':'black', 'border-width':'1px'}).apply(highlight_everyother).apply(bold_last)\nexpDFs=expDF.style.set_properties(**{'border': '1px blue solid !important','color':'black', 'border-width':'1px'}).apply(highlight_everyother).apply(bold_last)\n"

#### Generate Report

In [12]:
'''
#AGENCY:
revDFs.to_excel(writer, sheet_name=ag, startrow=startrow, startcol=startcol, index=False)
expDFs.to_excel(writer, sheet_name=ag, startrow=startrow+len(revDF)+2, startcol=startcol, index=False)

worksheet1 = writer.sheets[ag]
worksheet1.write(1, 0, 'Campus '+ ag, header_format)
worksheet1.write(2, 0, header, header_format)
worksheet1.write(3, 4, year, bold)
worksheet1.write(3, 9, pYear, bold)
worksheet1.write(startrow+len(revDF), 2, 'Total Income', boldBorderUnder)
worksheet1.write(startrow+len(revDF)+len(expDF)+2, 2, 'Total Expenses', boldBorderUnder)

#SAVE SHEET:
writer.save()
print("New Excel Report File created: ", fileName)
'''

'\n#AGENCY:\nrevDFs.to_excel(writer, sheet_name=ag, startrow=startrow, startcol=startcol, index=False)\nexpDFs.to_excel(writer, sheet_name=ag, startrow=startrow+len(revDF)+2, startcol=startcol, index=False)\n\nworksheet1 = writer.sheets[ag]\nworksheet1.write(1, 0, \'Campus \'+ ag, header_format)\nworksheet1.write(2, 0, header, header_format)\nworksheet1.write(3, 4, year, bold)\nworksheet1.write(3, 9, pYear, bold)\nworksheet1.write(startrow+len(revDF), 2, \'Total Income\', boldBorderUnder)\nworksheet1.write(startrow+len(revDF)+len(expDF)+2, 2, \'Total Expenses\', boldBorderUnder)\n\n#SAVE SHEET:\nwriter.save()\nprint("New Excel Report File created: ", fileName)\n'