# Quarterly Report GLBA

In [1]:
import pandas as pd
data=r'/kaggle/input/glbaqrt/GLBA.csv'
df=pd.read_csv(data)
df.head()

,GL Account,GL Description,Allocated Budget,Actual,% Used,Available,Budget Officer
0,2470650,REGGIE,0,823.00,0.0,-823.00,1234567
1,2470850,REGGIE,0,35.00,0.0,-35.00,1234567
2,2471050,REGGIE,0,-438252.78,0.0,438252.78,1234567
3,2471250,REGGIE,0,0.00,0.0,0.00,1234567
4,2471450,REGGIE,0,-185.10,0.0,185.10,1234567

In [2]:
df=df[['GL Account', 'Allocated Budget', 'Actual', 'Available']]
df.head()

   GL Account  Allocated Budget     Actual  Available
0     2470650                 0     823.00    -823.00
1     2470850                 0      35.00     -35.00
2     2471050                 0 -438252.78  438252.78
3     2471250                 0       0.00       0.00
4     2471450                 0    -185.10     185.10

In [3]:
df1=df[df['GL Account'] > 2470850]
df1.head()

   GL Account  Allocated Budget     Actual  Available
2     2471050                 0 -438252.78  438252.78
3     2471250                 0       0.00       0.00
4     2471450                 0    -185.10     185.10
5     2471650                 0 -626490.00  626490.00
6     2471850            162931   54139.75  108791.25

In [4]:
df2=df[df['GL Account'] > 2480000]
df2.head()

    GL Account  Allocated Budget   Actual  Available
47     2480050                 0     0.00       0.00
48     2480250                 0 -1192.90    1192.90
49     2480450              4840   880.87    3959.13
50     2480650             26200  9039.56   17160.44
51     2480850                 0 -6275.00    6275.00